### ISSUE TITLE
Project 

### ISSUE THREAD

**Issue by Renat2007** [amizu03/VAC-Bypass-Injector#2]
Hello.  Noticed that "Yatagarasu" was complaining when trying to put together a project.  Listen, amizu, maybe you can try to create the project yourself?

**Comment by amizu03** [comment]
I already compiled the source and linked the generated binaries on the Releases page. In case he wants to import the files (in a VS solution) himself, I already explained how to approach the problem. If he can't clearly describe the problem he is having, it is impossible for me to help him properly; I can't read his errors in Russian and it would be a waste of both of our times. I gave him my Discord contact information and waited for a reply, but I received none, so I closed the issue. Please contact me directly on Discord or wait for me to upload a second version of my injector (with the VS Solution) on a separate branch.

**Comment by Renat2007** [comment]
I think, he mean about file  "VAC-Bypass-Injector.sln"

**Comment by Renat2007** [comment]
And yes, surprisingly, I seem to have the same errors as Yatagarasu.  Today I will try to send bug reports

**Comment by Renat2007** [comment]
Hello.  Thanks for helping me, you are the best!  But, I noticed that in the "Releases" tab the file weighs 825 KB, but after my compilation it is only 41 KB.  What is the reason for this?

**Comment by amizu03** [comment]
I think I compiled in debug mode by accident, and all optimizations (including file size optimizations) were off. The release version was also not compiled in Visual Studio, but it is 1:1 the exact source code provided in the repository.

And yes, this issue was unrelated to the source code, it has to do with the way you configured your VS solution. I changed the usage instructions to be more clear about the compilation process, as well as adding a VS solution as a second option (even though you shouldn't need VS to compile, only MSVC++ build tools). If anyone raises similar issues I must make sure that the first thing they should do is provide a through description of their problem, or it won't be practical to help them. It makes it really hard for both of us.

Assuming issue is resolved; contact me on Discord for any further help unrelated to the project (as it was provided) in the repository.
